### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [jonscheiding/zsh-plugin-aws-vault-profiles#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by jonscheiding** [comment]
@unixorn thanks for adding me to that list and for the reminder to add a license! That's done.

**Comment by jonscheiding** [comment]
@unixorn Since there's already an `aws-vault` plugin on that list, I will rename this one to make it clearer what the difference is.

**Comment by unixorn** [comment]
You don't need to rename if you don't want to, I have a standard for dealing with duplicate names

```markdown
- [fooo (authora)](https://github/authora/foo) - blah
- [fooo (authorb)](https://github/authorb/foo-zsh) - blah
```

If you do decide to rename though, it's better to rename the repository in settings instead of deleting it and recreating it with a new name. If you rename the repo, github will redirect people automagically to the new name, otherwise links just break.

Let me know what you decide either in a comment here or by filing a PR against the list.

**Comment by jonscheiding** [comment]
@unixorn It made sense since their plugin is pretty generic and mine is targeting a specific usage mode of aws-vault.

Thanks for the invitation! https://github.com/unixorn/awesome-zsh-plugins/pull/1675
